# This workflow simplifies installing and building a Node.js project, then
# commits the built asset files to a target release branch.
name: Build to release branch

on:
  push:
    branches:
      - main
      - pluginification
  workflow_call:
    inputs:
      # Required inputs.
      source_branch:
        description: Name of source branch.
        required: true
        type: string
      release_branch:
        description: Name of target release branch. Will be updated with a merge commit that includes files within built_asset_paths.
        required: true
        type: string
      built_asset_paths:
        description: Generated assets to forcibly include in release branch commit. Overrides .gitignore.
        required: true
        type: string
      # Optional inputs.
      build_script:
        description: Command to run to build code. "npm ci; npm run build" by default.
        default: |
          npm ci
          npm run build
        required: false
        type: string
      commit_user_name:
        description: Name to use for release branch commit author.
        default: "Your friendly neighborhood GH Actions Bot"
        required: false
        type: string
      commit_user_email:
        description: Email to use for release branch commit email.
        default: "<>"
        required: false
        type: string
      node_version:
        required: false
        default: 22
        type: number

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'widgets/package-lock.json'

      - name: Merge and build
        uses: humanmade/hm-github-actions/.github/actions/build-to-release-branch@bbe801d037b61dd0fa0fcd7d208f6bf54d7ca1fd # v0.1.1
        with:
          source_branch: ${{ github.ref_name }} # Can change to "main" post-testing.
          release_branch: release
          built_asset_paths: widgets/dist
          build_script: |
            npm ci --prefix widgets
            npm run build --prefix widgets
          commit_user_name: "Your friendly neighborhood GH Actions Bot"
          commit_user_email: "<>"
