# This workflow simplifies installing and building a Node.js project, then
# commits the built asset files to a target release branch.
name: Build to release branch

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'widgets/package-lock.json'

      - name: Merge and build
        uses: humanmade/hm-github-actions/.github/actions/build-to-release-branch@bbe801d037b61dd0fa0fcd7d208f6bf54d7ca1fd # v0.1.1
        with:
          source_branch: main
          release_branch: release
          built_asset_paths: widgets/dist
          build_script: |
            npm ci --prefix widgets
            npm run build --prefix widgets
          commit_user_name: "Your friendly neighborhood GH Actions Bot"
          commit_user_email: "<>"
