name: Build to Release branch

on:
  push:
    branches:
      - main
      - pluginification

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: "Update release branch"
    uses: humanmade/hm-github-actions/.github/workflows/build-and-release-node.yml@bbe801d037b61dd0fa0fcd7d208f6bf54d7ca1fd # v0.1.1
    with:
      node_version: 22
      source_branch: ${{ github.ref_name }} # Can change to "main" post-testing.
      release_branch: release
      built_asset_paths: widgets/dist
      build_script: |
        npm ci --prefix widgets
        npm run build --prefix widgets
